### ISSUE TITLE
Link handbook/timetable at top of Ben course outline

### ISSUE THREAD

**Issue by AidenRay** [notionparallax/code1161base#14]
link this: https://www.handbook.unsw.edu.au/undergraduate/courses/2017/CODE1161.html
and/or this http://timetable.unsw.edu.au/2017/CODE1161.html.

Also change lecture time 9000 to 900 at top of course outline, maybe add semicolons.

**Comment by notionparallax** [comment]
Where did you think I might put semi-colons?
