### ISSUE TITLE
Cannot see/access Google Forms 1 and 2 Lecture 1

### ISSUE THREAD

**Issue by AidenRay** [notionparallax/code1161base#9]
![lecture1gglfrms](https://cloud.githubusercontent.com/assets/22095390/22858940/05cb79b0-f121-11e6-8e8a-d13edd2ddb26.JPG)

The formatting is there, but the box is blank/white. This is a repeated issue (not a one off occurrence).

The same issue occurs under getting registered -> Now fill in theses details: (before "back on topic")

**Comment by notionparallax** [comment]
What browser and os?

Could you see if an error comes up in your JavaScript console please?

This kind of thing is usually a CORS issue.

**Comment by AidenRay** [comment]
I'm using it in chrome on windows 10, I'll try it with my linux vm.

There are 6 errors and 2 warnings (8 errors if Adblock is on). 
Copying the errors/warnings loses the formatting, even when putting it in a markdown script formatting.
i'll post pics

**Comment by AidenRay** [comment]
![lecture1error1](https://cloud.githubusercontent.com/assets/22095390/22961676/0ba06fa8-f39c-11e6-8e88-97c37d09231b.JPG)
![lecture1error2](https://cloud.githubusercontent.com/assets/22095390/22961678/0ceb15de-f39c-11e6-9231-d6fa4fd30deb.JPG)
These are the errors from lecture 1 with AdBlock disabled

**Comment by notionparallax** [comment]
it's because I had sign in required. I've changed that and it works now.
